project:
  type: website

website:
  title: "Yuki's Website"
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: posts.qmd
      - experiences.qmd
      - icon: github
        href: https://github.com/Yuki620
      - icon: linkedin
        href: https://www.linkedin.com/in/yukiyu02/
format:
  html:
    page-layout: full
    code-overflow: wrap
    theme: cosmo
    css: styles.css
    math: mathjax

execute:
  freeze: auto


