---
title: "Work and Experience"
format: html
---

## 🎓 Education

### **Massachusetts Institute of Technology (MIT)** 

**Master of Business Analytics | 2024–2025**

- Coursework: Machine Learning, Optimization Methods, Analytics Edge
- Projects:
  - ML Project: Classification modeling and designing recommendation systems for health news tweets (Python)
  - Optimization Project: Optimizing EV charging station placements & charger allocations in Boston (Python, Julia)

### **University of California, Los Angeles (UCLA)**  

**Bachelor of Science | Applied Mathematics and Statistics & Data Science | 2020–2024**

---

## 💻 Experience

### **MIT Sloan / Comcast | Data Scientist, Capstone Team Member**  
_Spring 2025 – Present_

- Leveraging Natural Language Processing (NLP), Large Language Models (LLMs) to analyze real-time customer interactions in calls and optimize engagement strategies
- Implementing Retrieval-Augmented Generation (RAG) to identify customer issues in live calls and automate solution recommendations to improve customer satisfaction and reduce agent workload (Python, PySpark)

### **MIT Sloan / CMA CGM | Data Scientist, Analytics Lab Team Member**  
_Fall 2024_

- Forecasted U.S. import trends across 6 regions and 4 products using machine learning algorithms ARIMA, SARIMAX, XGBoost, and Random Forest, improving operational efficiency and strategic planning (Python, R)
- Created data-driven reports and presented insights to non-technical supervisors, ensuring data accessibility and informed decision-making

### **Academia Sinica | Research Intern**  
_Summer 2023_

- Refined a mathematical model of biofilm oscillations, using ODE modeling and RK4 solvers to enhance predictions of microbial behavior relevant to infection control (Python)
- Simulated the dynamics and behavior of individual-based biofilm models, providing insights into microbial interactions and biofilm development under varying conditions (NetLogo)

### **Mechanics Bank Auto Finance | Auto Risk Analyst (Part-Time)**  
_2022–2023_

- Developed an originations scorecard in a two-person team, completing most of the model building under mentor guidance to reduce overallocation risks and optimize resources for bank expansion
- Processed large-scale transactional data to create a development database for the scorecard (SAS, SQL, Excel)
- Built a logistic regression inference model to identify key predictors for risk assessment, optimizing resource allocation and improve decision-making (SQL, SAS)

---

## 🔧 Technical Skills

- **Languages:** Python, R, SQL, PySpark, Julia, SAS, C++
- **Tools:** Tableau, Databricks, Git, Excel
- **Methods:** Machine Learning, Optimization, Statistical Testing, Time Series Forecasting

---

## 📅 Additional Information

- Fluent in English and Chinese, Advanced in Japanese
- Avid runner and amateur baker 🌾✨

---

[Download Resume (PDF)](Resume.pdf)


